spring:
  application:
    name: hibernate-second-level-caching
#  config:
#    import: optional:configserver:http://config-server-url
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        cache:
          redis:
            servers: redis://localhost:6379
        format_sql: true
  #  cloud:
  #    vault:
  #      enabled: true
  #      generic:
  #        backend: secret
  #        default-context: application


